name: test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^0.13.5
  fluttertoast: ^8.1.1
  modal_progress_hud_nsn: ^0.3.0
  flutter_spinkit: ^5.1.0
  cached_network_image:
  intl:
  flutter_timezone:
  carousel_slider:
  flutter_rating_bar:
  simple_circular_progress_bar:
  flutter_calendar_carousel:
  sleek_circular_slider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/font/Quicksand-Light.ttf
          weight: 300
        - asset: assets/font/Quicksand-Regular.ttf
        - asset: assets/font/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/font/Quicksand-Bold.ttf
          weight: 700
